language: php
php:
- '7.0'
- hhvm
- nightly
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
notifications:
  slack:
    secure: KtOULv8670u+f1dZl+soSTWrNQamVn8zDV4VFsQnUjyMsN4Cw8aoEs6Bn6UcSjLTyNHnNyyz6qJMLNUGIQNACFSfCl3eZUyKbQXwGuNIjY6R70V29WMy/fv7E8bg2ELzNqyq0kzuAbPqpf0ao7Q6LDteKHQEZD8CdQMP3JZmvIXeeHCNYLDaUCQzQADA6Cd5fG48pN2WoDYo7Fb8yHDA7uN1ikfnL1cxgVUcUJ6z7W/4v7csRoUW7s40WlK2yXZWLe9u9YGefdl24jLRiQSrOi4UC8cnVhRK3GcJE55q0lMJkCK5WCGkbTZD3b4K+XmcVoh1BZWFVTJEV5QK55Pny9ZQsVRHWTgJe910tZiQwYcOZ1dKjoEZ2WGIHN6g2gJUUjq5uvpNHRwVRQKyHaddMSLADvKUEzXyYvIlEwXVq2o3mldxJth0vyTMq1R/Sx6BfrQAkCsVmdyKmHNY9qhbJEjKstYpFdScavr2epH78mYp+IroKKz+05ucivu8vjL6lVO0OrzMqaaKWrmHDbVm1DuTtNF5iI0oQYgk4JTwM6aBjzmFbWAX9Fo1vQqBowZ/VDd3cawZi7u37yXvKkn6kTOAHrXSykFHBjoelKbHVXeBiHrUK7VG+7YSwUC7GbiGm0r3+IDn99mjd4WIvRbKiFpQj4C+m7s1vr0nEHzQu9I=
